sudo: false
language: node_js
node_js:
  - "4.4"
  - "6.3"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - make tools deps
script:
  - make test
