service: sitechecker-slackbot-master

provider:
  name: aws
  runtime: nodejs4.3
  stage: ${opt:stage}
  region: ${opt:region}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "arn:aws:lambda:*:*:*"

package:
 include:
   - conf/
   - lib/

functions:
  handle:
    handler: lib/lambda.handle
    timeout: 90
    events:
      - http:
          path: handle
          method: post

plugins:
  - serverless-offline
